### ISSUE TITLE
How do you chat with documents using howso-engine without hallucinations?

### ISSUE THREAD

**Issue by Bardo-Konrad** [howsoai/howso-engine#148]
I used to chat with documents via local llm or openai and I experienced hallucinations.

How do you chat with documents using howso-engine without hallucinations?

**Comment by sdconrox** [comment]
Hey, @bardo-konrad! Thanks so much for reaching out. Currently, Howso is not yet ready for large volumes of language. We're aiming to get there on our long-term roadmap, with a few early preliminary/directional capabilities for small language data sets coming out later this year. 
 
For now, Howso can be used on structured data to make inferences without hallucinations. Engine can tell you when it is likely or unlikely to accurately make inferences from the data and can be driving by an LLM to do so.
 
At the moment, we are focused on the core technology of the Engine itself as well as enhancing the user experience by focusing on explainability, accuracy, and reliability.
 
We'd be interested to see what you build. Feel free to continue to tag us here or drop us a note at [info@howso.com](mailto:info@howso.com) to highlight your work with Engine. And keep following along with us here for more advancements towards text support!
